from tqdm import tqdm
from validators.validator import Validator
from dataset_dataclasses.question import Question
from models.model import Model
from db_datasets.db_dataset import DBDataset
from dataset_dataclasses.council_tracking import ValidationStageResult, QuestionVotes, ModelVote


class AmbiguityVerification(Validator):
    def __init__(self, db: DBDataset, models: list[Model]) -> None:
        self.db: DBDataset = db
        self.models: list[Model] = models

    def validate(self, questions: list[Question]) -> ValidationStageResult:
        valids: list[bool] = [True for _ in questions]

        # Generate SQLs for each question (without using the hidden knowledge) using all models
        sqls: list[list[str | None]] = [self.db.generate_sqls_unsafe(model, questions) for model in self.models]

        # Compare the SQL queries generated by different models to the GT SQL query
        # If the majority of models generate an equivalent SQL query, we consider the question not valid for the category
        question_votes: list[QuestionVotes] = []
        for i, question in tqdm(enumerate(questions), total=len(questions), desc="Comparing SQL results (ambiguity)"):
            gt_sql = question.sql
            assert gt_sql is not None, "GT SQL query is None."

            per_model_votes: list[ModelVote] = []
            equivalent_count = 0
            for midx, model_sqls in enumerate(sqls):
                sql = model_sqls[i]
                if sql is None:
                    per_model_votes.append(ModelVote(model_name=self.models[midx].model_name, vote=False))
                    continue

                is_equivalent = self.db.compare_query_results(
                    db_id=question.db_id,
                    predicted_sql=sql,
                    ground_truth_sql=gt_sql
                )
                per_model_votes.append(ModelVote(model_name=self.models[midx].model_name, vote=is_equivalent))
                if is_equivalent:
                    equivalent_count += 1

            if equivalent_count > len(self.models) / 2:
                valids[i] = False

            question_votes.append(QuestionVotes(
                question_index=i,
                question_text=question.question,
                votes=per_model_votes,
                aggregate_result=valids[i],
                removed=not valids[i],
            ))

        return ValidationStageResult(
            stage_name="ambiguity_verification",
            validities=valids,
            question_votes=question_votes,
        )
