from validators.validator import Validator
from dataset_dataclasses.question import Question
from models.model import Model
from db_datasets.db_dataset import DBDataset


class CheckAmbiguousness(Validator):
    def __init__(self, db: DBDataset, models: list[Model]) -> None:
        self.db: DBDataset = db
        self.models: list[Model] = models

    def validate(self, questions: list[Question]) -> list[bool]:
        valids: list[bool] = [True for _ in questions]

        # Generate SQLs for each question (without using the hidden knowledge) using all models
        sqls: list[list[str | None]] = [self.db.generate_sqls_unsafe(model, questions) for model in self.models]

        # Compare the SQL queries generated by different models to the GT SQL query
        # If the majority of models generate an equivalent SQL query, we consider the question not valid for the category
        for i, question in enumerate(questions):
            gt_sql = question.sql
            assert gt_sql is not None, "GT SQL query is None."

            equivalent_count = 0
            for model_sqls in sqls:
                sql = model_sqls[i]
                if sql is None:
                    continue

                if self.db.compare_query_results(
                        db_id=question.db_id,
                        predicted_sql=sql,
                        ground_truth_sql=gt_sql
                    ):
                    equivalent_count += 1
            
            # If majority generates equivalent SQL, mark as invalid
            if equivalent_count > len(self.models) / 2:
                valids[i] = False
        return valids
