from validators.validator import Validator
from dataset_dataclasses.question import Question
from models.model import Model
from db_datasets.db_dataset import DBDataset


class CheckAmbiguousness(Validator):
    def __init__(self, db: DBDataset, models: list[Model]) -> None:
        self.db: DBDataset = db
        self.models: list[Model] = models

    def validate(self, questions: list[Question]) -> list[bool]:
        valids: list[bool] = [True for _ in questions]

        # Generate the SQL generation prompts
        db_ids = [q.db_id for q in questions]
        questions_text = [q.question for q in questions]
        evidences = [q.evidence for q in questions]

        prompts = [self.db.get_prompt(
            db_id=db_id,
            question=question,
            evidence=evidence,
            num_rows=5
        ) for db_id, question, evidence in zip(db_ids, questions_text, evidences)]

        # Get the generated SQL queries from each model
        sqls: list[list[str | None]] = [[] for _ in questions]

        for model in self.models:
            model.init()
            outs = model.generate_batch(prompts)
            model.close()
            # Extract the last SQL query from each output
            results = [self.db.extract_last_sql_query_from_block(output) for output in outs]

            for i, sql in enumerate(results):
                sqls[i].append(sql)

        # Compare the SQL queries generated by different models to the GT SQL query
        # If at at least one model generates an equivalent SQL query, we consider the question not valid for the category
        for i, question in enumerate(questions):
            gt_sql = question.sql
            assert gt_sql is not None, "GT SQL query is None."

            for sql in sqls[i]:
                if sql is not None and self.db.compare_query_results(
                        db_id=question.db_id,
                        sql_query_1=gt_sql,
                        sql_query_2=sql
                    ):
                    valids[i] = False
                    break
        return valids
